# Generated by Django 2.1.3 on 2018-11-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
